/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.tagadvance.exception;

import java.io.Closeable;
import java.io.FileInputStream;
import java.util.stream.Stream;
import org.junit.jupiter.api.Test;

/**
 * Tests for {@link CheckedRunnable}, {@link CheckedComparator}, {@link CheckedConsumer},
 * {@link CheckedFunction}, and {@link CheckedPredicate}.
 */
class CheckedTest {

	@Test
	void testRunnable() {
		CheckedRunnable.of(CheckedTest::run).run();
	}

	private static void run() throws Exception {

	}

	@Test
	void testAll() {
		Stream.of("/dev/random", "/dev/zero")
			.sorted(CheckedComparator.of(CheckedTest::comparator))
			.filter(CheckedPredicate.of(CheckedTest::filter))
			.map(CheckedFunction.of(FileInputStream::new))
			.forEach(CheckedConsumer.of(Closeable::close));
	}

	private static int comparator(final Object o1, final Object o2) throws Exception {
		return 0;
	}

	private static boolean filter(final Object o) throws Exception {
		return true;
	}

}
